### ISSUE TITLE
Minimal IP use instructions

### ISSUE THREAD

**Issue by rbouqueau** [5G-MAG/Documentation-and-Architecture#22] opened 2021-10-23 14:21 UTC
I'm trying to replicate the setup for a minimalist use-case, software only. I've found the wiki and could clone and build most of the code (I haven't built everything to be honest). I was also present at the previous dev meetings. But I was not able to meet my ends. Did I miss something? Is it possible to address such a use-case?

Many thanks

**Comment by dsilhavy** [comment] 2021-11-01 07:21
* Even after running the modem as a service first? 
* Same error with `sudo`?

**Comment by rbouqueau** [comment] 2021-11-01 14:41
Running as sudo changes the behaviour.

I now get the following log:

```
$ sudo ./modem -f "../../5MHz_MCS16_1kHz25_DASH_q6a.raw" -b 5
...
modem[1656597]: DL TUN/TAP write error  Input/output error
modem[1656597]: DL TUN/TAP write error  Input/output error
modem[1656597]: DL TUN/TAP write error  Input/output error
modem[1656597]: DL TUN/TAP write error  Input/output error
modem[1656597]: CINR 15.33 dB
modem[1656597]: PDSCH: MCS 5, BLER 0, BER 0
modem[1656597]: MCCH: MCS 2, BLER 0, BER 0
modem[1656597]: MCH 0: MCS 16, BLER 0, BER 0.056443298969072166
modem[1656597]:     MTCH 0: LCID 1, TMGI 0x00000009f165, 238.1.1.95:40085
modem[1656597]:     MTCH 1: LCID 2, TMGI 0x00001009f165, 238.1.1.111:40101
modem[1656597]: -----
modem[1656597]: DL TUN/TAP write error  Input/output error
modem[1656597]: DL TUN/TAP write error  Input/output error
modem[1656597]: DL TUN/TAP write error  Input/output error
modem[1656597]: DL TUN/TAP write error  Input/output error
...
```

And the middleware:
```
$ ./mw
mw[1656650]: 5g-mag-rt mw v0.9.1 starting up
mw[1656650]: Starting FLUTE receiver on 238.1.1.95:40085 for TSI 0
# closing the modem:
mw[1656650]: Closing service with TMGI 00000009f165
mw[1656650]: receive_from error: Operation canceled
```

The Web server on port 3010 still serves empty pages at root and /modem-api endpoints.

Is there a step by step or a reference log so that I can investigate what goes wrong? Alternately could we setup a small call with devs to investigate this?

**Comment by dsilhavy** [comment] 2021-11-01 14:55
I think the error comes either from not running the modem as a service prior to launching it from the build folder or when using the wrong network adapter:

### Run as a service
For correct pre-configuring of the Receive Process at a system startup, it has to be run through systemd once:
````
sudo systemctl start 5gmag-rt-modem
sudo systemctl stop 5gmag-rt-modem
````

### Network config
See: https://github.com/5G-MAG/Documentation-and-Architecture/wiki/MBMS-Modem#multicast-routing

In order to find the right network interface use ifconfig. It might look similar to this: enp0s31f6: flags=4163<UP,BROADCAST,RUNNING,MULTICAST> with enp0s31f6 being the correct string in this case.

For changes to take effect, MBMS Modem needs to be restarted: sudo systemctl restart 5gmag-rt-modem.

If this does not work lets make a short call to check together

**Comment by rbouqueau** [comment] 2021-11-01 20:21
As a service it fails with the error:
```
$ sudo journalctl -u 5gmag-rt-modem
...
nov. 01 15:57:05 rose systemd[1]: Started 5gmag-rt-modem - 5G-MAG Reference Tools: MBMS Modem.
nov. 01 15:57:05 rose systemd[1661684]: 5gmag-rt-modem.service: Failed to determine user credentials: No such process
nov. 01 15:57:05 rose systemd[1661684]: 5gmag-rt-modem.service: Failed at step USER spawning /usr/share/5gmag-rt/pre_modem.sh: No such process
nov. 01 15:57:05 rose systemd[1]: 5gmag-rt-modem.service: Control process exited, code=exited, status=217/USER
nov. 01 15:57:05 rose systemd[1]: 5gmag-rt-modem.service: Failed with result 'exit-code'.
nov. 01 15:57:05 rose systemd[1]: 5gmag-rt-modem.service: Scheduled restart job, restart counter is at 9.
nov. 01 15:57:05 rose systemd[1]: Stopped 5gmag-rt-modem - 5G-MAG Reference Tools: MBMS Modem.
```

And:

```
$ ls -l /usr/share/5gmag-rt/pre_modem.sh 
-rwxr-xr-x 1 root root 712 23 oct.  15:30 /usr/share/5gmag-rt/pre_modem.sh
```

My OS is a Debian Testing.

**Comment by dsilhavy** [comment] 2021-11-04 09:59
Did you create a 5G MAG user : https://github.com/5G-MAG/rt-mbms-modem#41-adding-fivegmag-rt-user 

The `5gmag-rt-modem.service` uses the following user and group by default:

````
User=fivegmag-rt
Group=fivegmag-rt
````

**Comment by rbouqueau** [comment] 2021-11-04 10:59
Thanks. I hadn't realized these steps were mandatory. I initially thought I could build the independent tools and just launch them. I made a pass on the instructions and here is what I now get:

```
nov. 04 11:56:41 rose modem[2468926]: modem[2468926]: 5g-mag-rt modem v1.1.1 starting up
nov. 04 11:56:41 rose modem[2468926]: modem[2468926]: Initialising SDR
nov. 04 11:56:41 rose modem[2468926]: 5g-mag-rt modem v1.1.1 starting up
nov. 04 11:56:41 rose modem[2468926]: Initialising SDR
nov. 04 11:56:42 rose modem[2468926]: [INFO] Make connection: ''
nov. 04 11:56:42 rose modem[2468926]: terminate called after throwing an instance of 'std::runtime_error'
nov. 04 11:56:42 rose modem[2468926]:   what():  Failed to make connection with ''
nov. 04 11:56:42 rose systemd[1]: 5gmag-rt-modem.service: Main process exited, code=killed, status=6/ABRT
nov. 04 11:56:42 rose systemd[1]: 5gmag-rt-modem.service: Failed with result 'signal'.
nov. 04 11:56:42 rose systemd[1]: 5gmag-rt-modem.service: Scheduled restart job, restart counter is at 1333.
nov. 04 11:56:42 rose systemd[1]: Stopped 5gmag-rt-modem - 5G-MAG Reference Tools: MBMS Modem.
nov. 04 11:56:42 rose systemd[1]: Started 5gmag-rt-modem - 5G-MAG Reference Tools: MBMS Modem.
nov. 04 11:56:42 rose pre_modem.sh[2468931]: mbms_modem_tun
nov. 04 11:56:42 rose pre_modem.sh[2468933]: ioctl(TUNSETIFF): Device or resource busy
nov. 04 11:56:42 rose pre_modem.sh[2468935]: net.ipv4.conf.mbms_modem_tun.rp_filter = 0
```

**Comment by dsilhavy** [comment] 2021-11-04 12:32
Hm never saw this before. @kuehnhammer any idea?

Only reason I can think of is a misconfiguration for the network interface.

**Comment by kuehnhammer** [comment] 2021-11-04 12:36
Not really. Guessing from the error location, it might be that it cannot connect to the SDR.

Some ideas: Did the config file maybe get overwritten with defaults? Does the same error occur when decoding a sample file?

**Comment by rbouqueau** [comment] 2021-11-04 16:18
First of all, thank you for your help.

It now seems to work :) although on the command-line only... I can launch the Web UI. Beside a few crashes from the mw I can see the UI :)

However I can't launch the player because the local resources don't seem to be exposed e.g. ```Cannot GET /f/00001009f165/index.mpd``` when accessing http://localhost:3000/f/00001009f165/index.mpd (UI is at http://localhost:3000).

Any idea?

**Comment by kuehnhammer** [comment] 2021-11-05 10:35
Great to hear that it's working!

The files get served by the mw process, which handles the caching... so they won't be at port 3000 (rt-wui), but 3020.

There should be an nginx instance running at port 80 that distributes the HTTP requests to the appropriate process depending on their URL path, with the UI accessible at just http://localhost

Can you please try connecting to that URL?

#### If it doesn't work -->

 my first guess would be that this nginx isn't running, or does not have the rt-mbms configuration. This used to get installed by the mw process, but it looks like during the name change we didn't move it to wui as intended. I'll fix that ASAP.

For now, can you please try copying the nginx site configuration from here: 
https://github.com/5G-MAG/rt-mbms-mw/blob/874c753da43080c2294a3ddaea1d7ab2a4ea293e/supporting_files/obeca

to 
/etc/nginx/sites-available/rt-wui 

and then do Step 3 (Post installation configuration) from the rt-wui README (https://github.com/5G-MAG/rt-wui)

**Comment by rbouqueau** [comment] 2021-11-05 11:14
Thank you Klaus. Indeed I had to disable the nginx service because I was missing the https://github.com/5G-MAG/rt-mbms-mw/blob/874c753da43080c2294a3ddaea1d7ab2a4ea293e/supporting_files/obeca file. I didn't realize what its role was.

Now it works, many thanks! We can close if that's ok for you.

**Comment by dsilhavy** [comment] 2021-11-05 14:15
Thanks, closing

**Closed by dsilhavy** 2021-11-05 14:15 UTC
Labels: bug
